- hosts: all
  become: yes
  tasks:
   
    - name: install lamp stack
      apt:
        pkg:
          - php8.0-mysql
          - php8.0-curl
          - php8.0-json
          - php8.0-cgi
          - php8.0-xsl
          - php8.0-cgi
          - php8.0-gd
          - php8.0-mbstring
          - php8.0-zip
          - php8.0-xmlrpc
          - php8.0-soap
          - php8.0-intl
          - libapache2-mod-php
        state: present
        update_cache: yes 
